name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 3am

env:
  CI: true

jobs:
  install_deps:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm

  lint_js:
    name: Lint JS
    runs-on: ubuntu-latest
    needs: ['install_deps']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: ESLint
        run: pnpm lint

  test_type_checking:
    name: "Tests: Type Check"
    needs: ['install_deps']
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm tsc --noEmit
        working-directory: tests

  tests:
    name: Tests
    needs: ['install_deps']
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # how to say "not these" so we don't miss anything?
        # waiting on a an api from vitest for querying
        # the list of tests ahead of time before running them.
        slow-test:
          - defaults
          - addon-location
          - test-app-location
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm add --global ember-cli yarn
      - run: pnpm vitest --testNamePattern ${{ matrix.slow-test }}
        working-directory: tests

